---
title: "DATA_MONITORING"
author: "Carlos Couceiro Vlasak"
date: "2022-11-23"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(fredr)
library(forecast)
library(tidyverse)
library(lubridate)
library(hrbrthemes)
library(plotly)
library(tsDyn)
library(DT)
fredr_set_key("ed43ed5f8fa6abd9fb6236a0f64445f5")
```

## Current account Balance for CZ

```{r  message=FALSE, echo=FALSE, warning=FALSE}
dat<-fredr(series_id = "CZEB6BLTT02STSAQ")

#Base Model

dat$value<-as.ts(dat$value)
dat$date<-ymd(dat$date)
ser<-dat[,c(1,3)]

ggplot(ser, aes(x=date, y=value))+
  geom_line() +
  ggtitle('Total Balance as % of GDP for the Czech Republic') +
  theme_ipsum_tw(grid="XY", axis="xy") 


```

## Base Model

```{r message=FALSE, echo=FALSE, warning=FALSE}

ser$value %>% forecast(h=12)%>%autoplot()

```


## SETAR Model


```{r message=FALSE, echo=FALSE, warning=FALSE, error=FALSE}

grid<-selectSETAR(dat$value, m=3)

grid

fit<-setar(dat$value, mL=2, mH=3, th=-1.169727)

forec<-predict(fit, n.ahead = 7)

dates<-seq(as.Date(max(ser$date)), length.out=8 , by=90)

forec = as.data.frame((forec))

forec$dat<-subset(dates, dates > max(ser$date))

forec<-forec[,c(2,1)]
names(forec)<-names(ser)
ser1<-union_all(ser,forec)

ser1$part<-ifelse(ser1$date> max(ser$date), 'predicted', 'real')



ggplotly(ggplot(ser1, aes(x=date, y=value, color= part))+
  ggtitle(label = 'Total Balance as % of GDP for the Czech Republic') +
  theme_ipsum_tw(grid="XY", axis="xy") +
  geom_line()+
  geom_smooth())

```





